---
- name: Playbook que brinca com API de mentirinha
  hosts: localhost
  become: True
  tasks:
    # Lista as vulnerabilidades
    - name: Geraindo a variável json_vulnerabilidades, que guarda o json com TODAS as vulnerabilidades
      ansible.builtin.uri:
        url: http://192.168.122.5/api/3/vulnerabilities
        method: GET
        return_content: True
        status_code: 200
      register: json_vulnerabilidades

    - name: Gerando a variável lista_vuln, que guarda uma lista com as vulnerabilidades da microsoft
      ansible.builtin.set_fact:
        lista_vuln: "{{ json_vulnerabilidades.content | from_json | community.general.json_query('resources[*].id') | select('match', '^msft-') | list }}"

    - name: Gerando a variável lista_tudo, que guardará a lista contendo as vulnerabilidades e as máquinas afetadas
      ansible.builtin.set_fact:
        lista_tudo: []

    - name: Gerando a variável json_assets, que guarda um json com os assets conhecidos pela API
      ansible.builtin.uri:
        url: http://192.168.122.5/api/3/assets
        method: GET
        return_content: True
        status_code: 200
      register: json_assets

    - name: Gerando um LISTA contendo DICIONÁRIOS com os assets conhecidos pela API
      ansible.builtin.set_fact:
        estrutura_assets: "{{ json_assets.content | from_json | community.general.json_query('resources[*].{id: id, hostName: hostName}') }}"

    - name: Gerando lista com todas as vulnerabilidades e seus respectivos assets em formato de dicionário 
      ansible.builtin.include_tasks: tasks_criacao_lista_geral.yml
      loop: "{{ lista_vuln }}"

    - name: Exibe a lista lista_tudo
      ansible.builtin.debug:
        var: lista_tudo

    - name: Cria a lista lista_hosts_afetados, vazia
      ansible.builtin.set_fact:
        lista_hosts_afetados: []

    - name: Gera a lista de hosts afetados por vulnerailidades
      ansible.builtin.set_fact:
        lista_hosts_afetados: "{{ lista_hosts_afetados + [item.value] }}"
      loop: "{{ lista_tudo }}"

    - name: Exibe
      ansible.builtin.debug:
        var: lista_hosts_afetados
...